baseURL = "https://sgibson91.github.io/"
enableEmoji = true
languageCode = "en-gb"
theme = "anatole"

[params]
author = "Dr Sarah Gibson"
contentratio = 0.75
copyright = "Dr Sarah Gibson, 2019-{{ YEAR }}"
description = "Open Software - Open Infrastructure - Open Science"
doNotLoadAnimations = false
favicon = "favicons/"
images = ["images/profile_pic.jpg"]
indexDateFormat = "2006-01-02"
mainSections = ["blog"]
profilePicture = "images/profile_pic.jpg"
readMore = true
singleDateFormat = "2006-01-02"
title = "Dr Sarah Gibson"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sgibson91"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/drsarahlgibson"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:drsarahlgibson@gmail.com"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0003-0356-2765"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/drsarahlgibson/"

# [[params.socialIcons]]
# icon = "fas fa-calendar"
# title = "Calendar"
# url = "https://calendly.com/sgibson91"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"

#  [[menu.main]]
#  name = "Post Series"
#  weight = 3
#  identifier = "series"
#  url = "/series/"

  [[menu.main]]
  name = "Speaking"
  weight = 4
  identifier = "speaking"
  url = "/speaking/"

  [[menu.main]]
  name = "Past Talks"
  weight = 3
  identifier = "past-talks"
  url = "/past-talks/"
#  parent = "speaking"

  [[menu.main]]
  name = "Speaker Rider"
  weight = 4
  identifier = "speaker-rider"
  url = "/speaker-rider/"
#  parent = "speaking"

  [[menu.main]]
  name = "Pricing"
  weight = 5
  identifier = "pricing"
  url = "/pricing/"
#  parent = "speaking"

  [[menu.main]]
  name = "Media"
  weight = 6
  identifier = "media"
  url = "/media/"

  [[menu.main]]
  name = "Tags"
  weight = 7
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "CV"
  weight = 8
  url = "https://sgibson91.github.io/cv/"

[taxonomies]
series = "series"
tag = "tags"
