baseURL = "https://sgibson91.github.io/"
languageCode = "en-gb"
theme = "anatole"
enableEmoji = true

[params]
title = "Dr Sarah Gibson"
author = "Sarah Gibson"
description = "A collection of projects Sarah contributes to"
profilePicture = "images/profile_pic.jpg"
keywords = ""
favicon = "favicons/"
mainSections = ["blog"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sgibson91"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/drsarahlgibson"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:drsarahlgibson@gmail.com"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0003-0356-2765"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/drsarahlgibson/"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 300
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Speaking"
  weight = 400
  identifier = "speaking"
  url = "/speaking/"

  [[menu.main]]
  name = "Media"
  weight = 500
  identifier = "media"
  url = "/media/"

  [[menu.main]]
  name = "CV"
  weight = 600
  url = "https://sgibson91.github.io/cv/"
