baseURL: https://sgibson91.github.io/
theme: aafu
languageCode: en-gb
build:
  writeStats: true
params:
  title: Sarah Gibson - CV
  author: Sarah Gibson
  description: CV
  copyright: "Copyright Sarah Gibson, 2025"
  theme:
    mainTheme: dark
    showAttribute: false
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Sarah Gibson"
    tagline: "Software developer, DevOps engineer, and crazy cat lady known for automating the boring stuff"
    location: "United Kingdom"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-github
        url: "https://github.com/sgibson91"
        title: GitHub
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/drsarahlgibson"
        title: LinkedIn
      - icon: fab fa-orcid
        url: "https://orcid.org/0000-0003-0356-2765"
        title: Orcid
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: project
    - item: education
    - item: certifications
    - item: skill
    - item: publication
    # - hobbies
  aboutme:
    title: About Sarah
    icon: fas fa-fw fa-user
    description: >-
      Sarah Gibson is a highly skilled software and cloud infrastructure engineer with a strong track record of enabling open, data-driven research at scale.
      With 6+ years of experience at the intersection of technology, research, and education — spanning a pioneering tech nonprofit and a leading national institute for data science and AI — Sarah brings both deep technical expertise and a passion for collaboration.

      She specialises in designing and deploying cloud-based solutions that empower researchers to tackle complex, data-intensive challenges.
      Her work accelerates scientific discovery by making cutting-edge tools more accessible, scalable, and reproducible.
      An active contributor to the open-source community, Sarah champions open science practices and builds infrastructure that ensures research outputs are reusable and transparent.

      Driven by a belief in the power of interdisciplinary collaboration, Sarah thrives on partnering with domain experts to turn ambitious research goals into reality.
      Whether architecting robust cloud systems or advocating for open, equitable technology, she's committed to creating lasting impact across research and education.
  experience:
    title: Experience
    icon: fas fa-fw fa-briefcase
    list:
      - position: Open Source Infrastructure Engineer
        dates: 2021 - *Present*
        url: "https://2i2c.org"
        company: 2i2c
        details: |1-
          - Designed, deployed, and maintained resilient cloud infrastructure across AWS, Azure, and GCP, including production-grade Kubernetes clusters.
          - Defined and implemented infrastructure as code (IaC) and CI/CD pipelines to automate deployments and improve system reliability and delivery speed.
          - Collaborated with stakeholders to gather requirements and architect scalable, user-centric solutions aligned with operational and business goals.
          - Contributed upstream to open-source projects, delivering new features and ensuring long-term sustainability of critical software ecosystems.
          - Led end-to-end development and delivery of new product features, from scoping stakeholder needs to successful launch.
          - Collaborated effectively within a globally distributed, agile team, driving progress across time zones and disciplines.
          - Delivered high-quality operational support, resolving incidents and addressing customer issues in a high-availability environment.
      - position: Research Software Engineer
        dates: 2018 - 2021
        url: "https://turing.ac.uk"
        company: The Alan Turing Institute
        details: |1-
          - Collaborated closely with researchers and stakeholders across the Turing network to develop software solutions for data-intensive research aligned with Turing Challenge Areas.
          - Led the end-to-end delivery of research software projects, applying best practices in software engineering—including version control, modular design, and testing—to ensure maintainability and reproducibility.
          - Built and automated computational infrastructure and data pipelines, performed data wrangling and analysis, and delivered insights through clear documentation, technical reports, presentations, and blog posts.
          - Managed projects from inception to delivery, coordinating across multidisciplinary teams to align technical implementation with research goals.
          - Notable projects: [_The Turing Way_](https://www.turing.ac.uk/research/research-projects/turing-way)
            and [Living with Machines](https://www.turing.ac.uk/research/research-projects/living-machines)
  education:
    title: Education
    icon: fas fa-fw fa-graduation-cap
    list:
      - degree: Astrophysics Ph.D.
        college: University of Leicester
        dates: 2015 - 2018
        thesis_title: "Understanding the Most Powerful Explosions in the Universe"
      - degree: MPhys Physics with Astrophysics
        college: University of Hull
        dates: 2010 - 2014
  publication:
    title: Publications
    icon: fas fa-fw fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
    list:
      - title: >-
          Fallback accretion on to a newborn magnetar: long GRBs with giant X-ray flares
        authors: "S.L. Gibson, G.A. Wynn, B.P. Gompertz, P.T. O'Brien"
        date: "2018"
        journal: "Monthly Notices of the Royal Astronomical Society 478 (4), 4323–4335"
        url: "https://doi.org/10.1093/mnras/sty1363"
        type: Journal Articles
      - title: >-
          Fallback accretion on to a newborn magnetar: short GRBs with extended emission
        authors: "S.L. Gibson, G.A. Wynn, B.P. Gompertz, P.T. O'Brien"
        date: "2017"
        journal: "Monthly Notices of the Royal Astronomical Society 470 (4), 4925–4940"
        url: "https://doi.org/10.1093/mnras/stx1531"
        type: Journal Articles
  project:
    title: Projects
    icon: fas fa-fw fa-project-diagram
    list:
      - title: The Turing Way
        url: "https://book.the-turing-way.org/"
        role: Co-Lead of Infrastructure Working Group
        dates: 2018 - *Present*
        details: |1-
          - Designed and executed strategic roadmaps for implementing and maintaining scalable infrastructure aligned with long-term project goals.
          - Assessed and prioritised team activities to maximise impact and drive progress toward the group’s strategic objectives.
          - Introduced and led the adoption of Agile workflows, improving transparency, accountability, and team efficiency.
          - Co-led a cross-functional working group, contributing to strategic direction, operational management, and the successful onboarding of new members.
      - title: JupyterHub and Binder
        url: "https://jupyterhub-team-compass.readthedocs.io/en/latest/"
        role: Maintainer
        dates: 2019 - 2025
        details: |1-
          - Recognised as a [Jupyter Distinguished Contributor](https://blog.jupyter.org/congratulations-distinguished-contributors-bc349fa60d68)
            in 2022 for significant contributions to the Jupyter ecosystem and advancing open-source initiatives.
          - Operated and maintained a public cloud platform delivering reproducible, containerized computing environments for research and education at scale.
          - Automated and parallelized core deployment processes using CI/CD pipelines to enable fast, reliable, and consistent platform updates.
          - Served as technical lead and primary maintainer for a private BinderHub deployment at the Turing Institute, ensuring stability, scalability, and performance.
          - Secured and managed a $10K infrastructure grant to support the deployment and scaling of cloud resources, including traffic sharing with mybinder.org.
          - Facilitated monthly community calls, fostering collaboration, gathering feedback, and guiding technical priorities for ongoing platform development.
      - title: Software Sustainability Institute/University of Edinburgh
        role: Independent Consultancy
        dates: Oct. 2023 - Jun. 2024
        details: |1-
          - Designed and delivered training on software engineering best practices - focusing on version control, code readability, and FAIR principles - for a research software course.
          - https://github.com/carpentries-incubator/fair-research-software
      - title: Software Sustainability Institute
        url: "https://www.software.ac.uk/blog/announcing-2020-software-sustainability-institute-fellows"
        role: Fellow
        dates: 2020
        details: |-
          - Initiated and cultivated a community of practice focused on leveraging cloud infrastructure to enable reproducible research, fostering collaboration, knowledge sharing, and peer support across disciplines.
      - title: OLS
        url: "https://we-are-ols.org/"
        role: Mentor
        dates: Feb. 2021 - Jan. 2022
        details: |1-
          - Mentored cohorts in open leadership development, guiding them in growing sustainable open science projects and fostering inclusive, collaborative communities.
  certifications:
    title: Certifications
    panelId: certs-panel
    icon: fas fa-fw fa-certificate
    list:
      - course: "LFS258 Kubernetes Fundamentals"
        course_url: "https://www.credly.com/badges/5fcebe78-bcac-4f73-bd46-692782142e15/public_url"
        org: The Linux Foundation
        org_url: "https://www.linuxfoundation.org/"
        awarded: "Aug. 20, 2024"
      - course: "Scientific Community Engagement Fundamentals"
        course_url: "https://api.badgr.io/public/assertions/OWeiqSTrQWy2od3P6GDQkA"
        org: "Center for Scientific Collaboration and Community Engagement"
        org_url: "https://www.cscce.org/"
        awarded: "Nov. 14, 2022"
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-fw fa-cogs
    list:
      - area: Technical
        skills:
          - name: AWS
            level: working
          - name: Azure
            level: working
          - name: CI/CD
            level: practitioner
          - name: DevOps Engineering
            level: working
          - name: Docker
            level: working
          - name: filesystem management
            level: awareness
          - name: git
            level: practitioner
          - name: GitHub
            level: practitioner
          - name: GitHub Actions
            level: practitioner
          - name: Google Cloud
            level: working
          - name: Grafana
            level: awareness
          - name: Helm
            level: working
          - name: Jupyter
            level: practitioner
          - name: Kubernetes
            level: working
          - name: Linux
            level: working
          - name: Prometheus
            level: awareness
          - name: Python
            level: practitioner
          - name: Site Reliability Engineering
            level: working
          - name: Terraform
            level: working
          - name: testing
            level: working
      - area: Interpersonal
        skills:
          - name: "Actively support team development through mentoring and knowledge sharing"
          - name: "Experienced in Agile methodologies, contributing to high-performing, iterative development"
          - name: "Lead effective meetings, fostering collaboration and clarity"
          - name: "Represents teams at conferences, stakeholder sessions, and client meetings with clarity and professionalism"
          - name: "Cultivate positive team culture through collaboration, empathy, and accountability"
          - name: "Excel in partnering across functional areas and disciplines"
          - name: "Manage multiple, complex initiatives while maintaining attention to detail and strategic alignment"
      - area: Communication
        skills:
          - name: "Exceptional verbal and written communicator demonstrated through delivery of"
          - name: technical papers
          - name: research publications
          - name: clear and comprehensive documentation
          - name: engaging conference presentations
          - name: training sessions
          - name: community outreach initiatives
          - name: technical blog content
  # hobby:
  #   title: Hobbies
  #   icon: fas fa-fw fa-gamepad
  #   list:
  #     - hobby: Reading
  #     - hobby: Travelling
  #     - hobby: Hiking
  #     - hobby: Playing guitar
  #     - hobby: Embroidery
  