baseURL = "https://sgibson91.github.io/"
languageCode = "en-gb"
theme = "anatole"
enableEmoji = true

[params]
title = "Dr Sarah Gibson"
author = "Dr Sarah Gibson"
description = "Open Software - Open Infrastructure - Open Science"
profilePicture = "images/profile_pic.jpg"
keywords = ""
favicon = "favicons/"
mainSections = ["blog"]
images = ["images/profile_pic.jpg"]
doNotLoadAnimations = false
copyright = "2019-{{ YEAR }}"
contentratio = 0.8
readMore = true

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sgibson91"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/drsarahlgibson"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:drsarahlgibson@gmail.com"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0003-0356-2765"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/drsarahlgibson/"

[[params.socialIcons]]
icon = "fas fa-calendar"
title = "Calendar"
url = "https://calendly.com/sgibson-2i2c"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Speaking"
  weight = 3
  identifier = "speaking"
  url = "/speaking/"

  [[menu.main]]
  name = "Media"
  weight = 4
  identifier = "media"
  url = "/media/"

  [[menu.main]]
  name = "CV"
  weight = 5
  url = "https://sgibson91.github.io/cv/"
