baseURL = "https://sgibson91.github.io/"
enableEmoji = true
languageCode = "en-gb"
theme = "anatole"

[params]
author = "Dr Sarah Gibson"
contentratio = 0.65
copyright = "Dr Sarah Gibson, 2019-{{ YEAR }}"
description = "Open Software - Open Infrastructure - Open Science"
doNotLoadAnimations = false
favicon = "favicons/"
images = ["images/profile_pic.jpg"]
indexDateFormat = "2006-01-02"
mainSections = ["blog"]
profilePicture = "images/profile_pic.jpg"
readMore = true
singleDateFormat = "2006-01-02"
title = "Dr Sarah Gibson"
oldContentWarning = true
oldContentDuration = 365
relatedPosts = true
numberOfRelatedPosts = 3

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sgibson91"

# [[params.socialIcons]]
# icon = "fab fa-twitter"
# title = "Twitter"
# url = "https://twitter.com/drsarahlgibson"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:drsarahlgibson@gmail.com"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0003-0356-2765"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/drsarahlgibson/"

# [[params.socialIcons]]
# icon = "fas fa-calendar"
# title = "Calendar"
# url = "https://calendly.com/sgibson91"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Portfolio"
  weight = 3
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Tags"
  weight = 4
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "CV"
  weight = 6
  url = "https://sgibson91.github.io/cv/"

  [[menu.footer]]
  name = "License"
  weight = 1
  identifier = "license"
  url = "/license/"

[taxonomies]
series = "series"
tag = "tags"

## Related posts
[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
