name: Merge Pal

on:
  status: {}
  push:
    branches-ignore:
      - master
  pull_request_review:
    types:
      - submitted
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
