name: Automatically Tweet about new Blog Posts

on:
  push:
    branches:
      - "auto-tweet-blogs"

jobs:
  auto-tweet-blogs:
    runs-on: ubuntu-latest
    # environment: auto-tweet

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.1.0

      - name: Analyse changed files
        uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate URL
        run: |
          for filename in ${{ steps.changed-files.outputs.added_modified }}; do
            if [[ $filename == *.md ]]; then
              echo "FULL_MD_FILENAME=$filename" >> $GITHUB_ENV
              MD_FILENAME=$(echo $filename | awk -F'/' '{printf $NF}')
              FILENAME=${MD_FILENAME%%.md}
              echo "URL=https://${{ github.event.repository.name }}/blog/${FILENAME}/" >> $GITHUB_ENV
            fi
          done

      - name: Read YAML frontmatter
        run: |
          sed -n '/---/,/---/p' ${{ env.FULL_MD_FILENAME }}

      # - name: Send tweet
      #   uses: ethomson/send-tweet-action@v1.0.0
      #   with:
      #     status: "✨ New blog post! ✨\n\n{{ title }}\n\n{{ url }}"
      #     consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      #     consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      #     access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      #     access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
