name: Autoupdate the Website Theme

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

jobs:
  autoupdate-theme:
    runs-on: ubuntu-latest
    environment: github-app-token

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run git submodule command
        run: |
          git submodule update --remote

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update anatole theme
          branch: update-theme
          title: Update website theme
          body: "Automated update of git submodule that contains the website theme"
          labels: website
          token: ${{ steps.generate_token.outputs.token }}
