name: Automatically Tweet about new Blog Posts

on:
  push:
    branches:
      - "auto-tweet-blogs"

jobs:
  auto-tweet-blogs:
    runs-on: ubuntu-latest
    # environment: auto-tweet

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.1.0

      - name: Analyse changed files
        uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Isolate filename
        run: |
          echo "${{ steps.changed-files.outputs.added }}" | awk -F'/' '{printf $NF}'

      # - name: Send tweet
      #   uses: ethomson/send-tweet-action@v1.0.0
      #   with:
      #     status: "✨ New blog post! ✨\n\n{{ title }}\n\n{{ url }}"
      #     consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      #     consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      #     access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      #     access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
